FROM python:3.12-slim
RUN pip install --no-cache-dir --default-timeout=1000 --retries 20 mlflow==2.16.2 && useradd -m -u 1000 app && mkdir /mlflow && chown app /mlflow
USER app
EXPOSE 5000
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]
